In [1]:
import numpy as np 

# Numpy

Main usages comes in when we are dealing with:
- arrays;
- matrices;
- mathematical operations on these structures;
  

In [2]:
arr1 = np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
print(arr1.reshape(5,1))
print(arr1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5,)


In [9]:
print(arr1.reshape(1,5))
print(arr1.shape)

[[1 2 3 4 5]]
(5,)


In [11]:
# 2d array

arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [17]:
# creating arrays using hardcodings
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [22]:
# creating matrix of ones
np.ones((2,2),'int')

array([[1, 1],
       [1, 1]])

In [30]:
# identity matrix creation 
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [32]:
print('Array:\n', arr1)
print('Shape:', arr1.shape)
print('Number of dimensions:', arr1.ndim)
print('Size (number of elements):', arr1.size)
print('Data type:', arr1.dtype)
print('Item size (in bytes):', arr1.itemsize)

Array:
 [1 2 3 4 5]
Shape: (5,)
Number of dimensions: 1
Size (number of elements): 5
Data type: int64
Item size (in bytes): 8


In [33]:
# arrays support vecotor operations 

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

# addition
print('Addition:', arr1+arr2)

# substraction 
print('Substraction:', arr1-arr2)

# multiplication
print('Multiplication:', arr1*arr2)

# division
print('Division:', arr1/arr2)

Addition: [ 7  9 11]
Substraction: [-3 -3 -3]
Multiplication: [10 18 28]
Division: [0.4        0.5        0.57142857]


In [34]:
# also np has default functions such as sin, exp, sqrt and so on

arr1 = np.array([1,2,3])
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [36]:
# slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('array:\n', arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
# first number is the rows manipulation and the second one is for column manipulation
print(arr[0:, 2:])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [45]:
# also using this manipulation method array values can be changed accordingly
arr[0:,3:] = 1000
print(arr)

[[   1    2    3 1000]
 [   5    6    7 1000]
 [   9   10   11 1000]]


In [46]:
# arrays are also a comfortable way of applying statistical methods, such as normalization

data = np.array([1,2,3,4,5,6,7,8])

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print('normalized data:', normalized_data)

normalized data: [-1.52752523 -1.09108945 -0.65465367 -0.21821789  0.21821789  0.65465367
  1.09108945  1.52752523]


In [51]:
# also they support logical operations for data manipulation
data[(data > 5) & (data < 7)]

array([6])