In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import string

In [12]:
text ='''
the food is good.
the food is bad.
pizza is amazing.
'''

In [23]:
text = text.lower()
text = text.translate(str.maketrans("", "", string.punctuation))
words = text.split()
vocab = sorted(set(words))

In [18]:
word_to_index = {word: idx for idx, word in enumerate(vocab)}

In [20]:
word_to_index

{'amazing': 0, 'bad': 1, 'food': 2, 'good': 3, 'is': 4, 'pizza': 5, 'the': 6}

In [24]:
one_hot_encoded = np.eye(len(vocab))[[word_to_index[word] for word in words]]

In [25]:
print("Vocabulary:", vocab)
print("One-hot encoded sentence:")
print(one_hot_encoded)

Vocabulary: ['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']
One-hot encoded sentence:
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


- Advantages:
  - easy to implement (onehotencoder in sklearn, pd.get_dummies);


- Disadvantages:
  - sparse matrix, this is problematic since in the end of the day it gives out overfitting, since during the training this matrix would be fitting only for the training data; 
  - no semantic meaning is captured, since we are only providing 1 and 0;
  - also it is bad at dealing with super large vocabulary sizes;
