In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
sent = [
        'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
]

In [5]:
# defining the vocab size
vocab = 10000

In [8]:
# one hot representation

one_hot_repr = [one_hot(words, vocab) for words in sent]
one_hot_repr
# here we can see what kind of index that word was given out like in one hot encoding

[[3334, 4048, 8560, 2130],
 [3334, 4048, 8560, 4052],
 [3334, 9193, 8560, 6308],
 [4988, 3409, 7758, 5709, 5184],
 [4988, 3409, 7758, 5709, 4973],
 [4075, 3334, 8279, 8560, 7163],
 [958, 3636, 6947, 5709]]

In [21]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import Input
import numpy as np

In [14]:
sent_lenght = 8

# in order to make all of the sentences same lenght we use pad_sequence
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 3334 4048 8560 2130]
 [   0    0    0    0 3334 4048 8560 4052]
 [   0    0    0    0 3334 9193 8560 6308]
 [   0    0    0 4988 3409 7758 5709 5184]
 [   0    0    0 4988 3409 7758 5709 4973]
 [   0    0    0 4075 3334 8279 8560 7163]
 [   0    0    0    0  958 3636 6947 5709]]


In [19]:
# feature representation

dim = 10

In [22]:
# model init

model = Sequential()
model.add(Input(sent_lenght))
model.add(Embedding(vocab, dim))
model.compile('adam', 'mse')

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 107ms/step


array([[[ 0.03149729,  0.01336241,  0.00450628,  0.01985773,
         -0.04705435,  0.0301476 ,  0.04309617,  0.0436745 ,
          0.04880336, -0.03248961],
        [ 0.03149729,  0.01336241,  0.00450628,  0.01985773,
         -0.04705435,  0.0301476 ,  0.04309617,  0.0436745 ,
          0.04880336, -0.03248961],
        [ 0.03149729,  0.01336241,  0.00450628,  0.01985773,
         -0.04705435,  0.0301476 ,  0.04309617,  0.0436745 ,
          0.04880336, -0.03248961],
        [ 0.03149729,  0.01336241,  0.00450628,  0.01985773,
         -0.04705435,  0.0301476 ,  0.04309617,  0.0436745 ,
          0.04880336, -0.03248961],
        [ 0.03826091,  0.00797528, -0.03371777,  0.04505731,
         -0.03921101, -0.03065673,  0.01441935, -0.00047576,
          0.04151377,  0.00228417],
        [-0.04976831,  0.00916167, -0.03846259, -0.04244852,
         -0.04057728, -0.0167384 ,  0.00592283, -0.0265486 ,
          0.02733675,  0.0040714 ],
        [ 0.03070581, -0.01567813,  0.03820611, -0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 3334, 4048, 8560, 2130], dtype=int32)

In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 26ms/step


array([[ 0.03149729,  0.01336241,  0.00450628,  0.01985773, -0.04705435,
         0.0301476 ,  0.04309617,  0.0436745 ,  0.04880336, -0.03248961],
       [ 0.03149729,  0.01336241,  0.00450628,  0.01985773, -0.04705435,
         0.0301476 ,  0.04309617,  0.0436745 ,  0.04880336, -0.03248961],
       [ 0.03149729,  0.01336241,  0.00450628,  0.01985773, -0.04705435,
         0.0301476 ,  0.04309617,  0.0436745 ,  0.04880336, -0.03248961],
       [ 0.03149729,  0.01336241,  0.00450628,  0.01985773, -0.04705435,
         0.0301476 ,  0.04309617,  0.0436745 ,  0.04880336, -0.03248961],
       [ 0.03826091,  0.00797528, -0.03371777,  0.04505731, -0.03921101,
        -0.03065673,  0.01441935, -0.00047576,  0.04151377,  0.00228417],
       [-0.04976831,  0.00916167, -0.03846259, -0.04244852, -0.04057728,
        -0.0167384 ,  0.00592283, -0.0265486 ,  0.02733675,  0.0040714 ],
       [ 0.03070581, -0.01567813,  0.03820611, -0.00282041,  0.02944256,
         0.0368807 ,  0.03874033,  0.00855193